// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaHukIeQtLWKwPLjNXGCsw8MAH5WLJum4',
    appId: '1:813906705019:android:b191a3a42d95ad4abb40de',
    messagingSenderId: '813906705019',
    projectId: 'flutter-masterclass-fcb50',
    storageBucket: 'flutter-masterclass-fcb50.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAx6hfCyZGNWgHchsQOXgJ8Oz8gbsgilFY',
    appId: '1:813906705019:ios:c973889cb98db9febb40de',
    messagingSenderId: '813906705019',
    projectId: 'flutter-masterclass-fcb50',
    storageBucket: 'flutter-masterclass-fcb50.firebasestorage.app',
    iosBundleId: 'com.example.flutterRpg',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCX5LtUghxjWcY2rUubpRf_HngALLHWV8w',
    appId: '1:813906705019:web:4a08f481ee2f66d6bb40de',
    messagingSenderId: '813906705019',
    projectId: 'flutter-masterclass-fcb50',
    authDomain: 'flutter-masterclass-fcb50.firebaseapp.com',
    storageBucket: 'flutter-masterclass-fcb50.firebasestorage.app',
    measurementId: 'G-DV5HF8CER3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCX5LtUghxjWcY2rUubpRf_HngALLHWV8w',
    appId: '1:813906705019:web:c476722c53735704bb40de',
    messagingSenderId: '813906705019',
    projectId: 'flutter-masterclass-fcb50',
    authDomain: 'flutter-masterclass-fcb50.firebaseapp.com',
    storageBucket: 'flutter-masterclass-fcb50.firebasestorage.app',
    measurementId: 'G-ZLFJDBMCEZ',
  );

}